version: '3.8'
services:
  pada-mysql-dev-db:
    container_name: pada-mysql-container
    image: mysql:8
    restart: always
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - .env
    networks:
      - pada-network

  pada-api-dev:
    container_name: pada-api-dev
    build:
        context: .
        target: development
        dockerfile: ./Dockerfile
    image: pada-api-dev
    restart: always
    command: npm run start:debug
    ports:
        - 3000:3000
        - 9229:9229
    networks:
        - pada-network
    volumes:
      - ./:/usr/src/pada-api/
    # depends_on:
    #   - pada-mysql-dev-db
    links:
      - "pada-mysql-dev-db"
    env_file:
      - .env

volumes:
  pada-mysql-dev-db:
    name: pada-db

networks:
  pada-network:
 
