version: "3"

services:
  database:
    image: 'postgres:13.7-alpine'
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ".:/app:rw"

  backend:
    build:
      context: .
    command: npm run start
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - database
    env_file: .env
    container_name: nest-docker-postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4-demo
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - database

