-- AlterTable
ALTER TABLE `adoptions` MODIFY `gender` ENUM('MALE', 'FEMALE', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `adoptionState` ENUM('INPROGRESS', 'ADOPTED', 'CANCELED') NOT NULL DEFAULT 'INPROGRESS';
